const mongoose=require("mongoose");
const {ObjectId}=mongoose.Schema;


var memberSchema=new mongoose.Schema({
 
    mfname:{
        type:String,
        maxlength:120,
        minlength:3,
        required:true
    },
    mlname:{
        type:String,
        maxlength:120,
        minlength:3,
        required:true
    },
    memail:{
        type:String,
        trim:true,
        required:true
    },
    mphone:{
        type:Number,
        required:true
    },
    moptional_phone:{
        type:String,
        trim:true,
        default:"NILL"
    },
    moptional_contactperson:{
        type:String
    },
    madress:{
        type:String,
        default:""
    },
    mstate:{
        type:String,
        default:""
    },
    mcity:{
        type:String,
        default:""
    },
    mlocation:{
        type:String,
        default:""
    },
    mpincode:{
        type:Number
    },
    dateofbirth:{
        type:String
    },
    height:{
        type:Number
    },
    heightUnit:{
        type:String,
        default:"Feet(ft)"
    },
    weight:{
        type:Number
    },
    weightUnit:{
        type:String,
        default:"Kilometer (kg)"
    },
    workout_experience:{
        type:String
    },
    body_type:{
        type:String
    },
    fitness_goal:{
        type:String
    },
    id_document:{
        type:String
    },
    other_detail:{
        type:String
    },
    medicalHealth:{
        type:ObjectId,
        ref:"MedicalHealth"
    },
    //planner info   
    planner:{
        type:String,
        default:""
    },
    planner_name:{
        type:String,
        default:""
    },
    planner_startDate:{
        type:String
    },
    planner_duration:{
        type:Number
    },
    planner_remark:{
        type:Boolean,
        default:false
    },
    level:{
        type:String,
        default:"beginner"
    },
    progress:{
        type:Number,
        default:0
    },
    gymbadge:{
        type:Number,
        default:0
    },
    instructor:{
        name:{
            type:String,
        },
        user:{
            type:ObjectId,
            ref:"User"
        }
    },
    appoientmentList:[{
        type:ObjectId,
        ref:"Appoienment"
    }],
    notification_list:[{type:ObjectId,ref:"Notification"}],
    workout_reports_list:[{
        type:ObjectId,
        ref:"WorkoutReport"
    }],
    medical_report_list:{
        type:ObjectId,
        ref:"MedicalReport"
    },
    measurement_list:[{
        type:ObjectId,
        ref:"Measurement"
    }],
    fitnessTest:[{
        type:ObjectId,
        ref:"FitnessTest"
    }],
    phybodycomp_list:[{
        type:ObjectId,
        ref:"PhyBodyCompTest"
    }], 
    calender:{
        type:ObjectId,
        ref:"Calender"
    },
    branchId:{
        type:ObjectId,
        ref:"Branch"
    }, 
    active:{
        type:Boolean,
        default:true
    }
});

module.exports=mongoose.model("Member",memberSchema);